apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: floaty-backend
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.floatyfly.com`)
      priority: 10
      services:
        - name: svc-floaty-backend
          port: 80
  tls: {}