apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: floaty-backend
spec:
  rules:
  - host: api.floatyfly.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-floaty-backend
            port:
              number: 80