apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: floaty-backend
  namespace: floaty
  labels:
    app: floaty-backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: floaty-backend
  endpoints:
  - port: management
    path: /actuator/prometheus
    interval: 30s
