cronjob:
  schedule: '@daily'
  concurrencyPolicy: Forbid

image:
  tag: '38'

renovate:
  config: |
    {
      "platform": "github",
      "endpoint": "https://api.github.com/",
      "repositories": ["FloatyFly/floaty-backend"],
      "onboarding": true,
      "requireConfig": "optional",
      "enabledManagers": ["maven"],
      "packageRules": [
        {
          "matchManagers": ["maven"],
          "matchUpdateTypes": ["patch", "minor"],
          "groupName": "Maven non-major updates",
          "groupSlug": "maven-non-major"
        },
        {
          "matchManagers": ["maven"],
          "matchUpdateTypes": ["major"],
          "groupName": "Maven major updates",
          "groupSlug": "maven-major"
        }
      ]
    }

envFrom:
  - secretRef:
      name: renovate-env

pod:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

persistence:
  cache:
    enabled: true
    storageSize: 2Gi
